
def BadDict():
    bad_dict = {"constitutive enzymes":,
    "corticosteroids":,
    "cosmid":"Enzymes 	required at all times by a cell and present at some constant level; 	for example, many enzymes of the central metabolic pathways. 	Sometimes called "housekeeping enzymes."",
    "eotransport":"Steroid hormones formed by the adrenal cortex.",
    "coupled reactions":"A 	cloning vector, used for cloning large DNA fragments; generally 	contains segments derived from bacteriophages and various plasmids.",
    "covalent bond":"The simultaneous transport, by a single 	transporter, of two solutes across a membrane. See antiport, 	symport.",
    "cristae":"Two chemical reactions that 	have a common intermediate and thus a means of energy transfer from 	one to the other.", 
    "cyclic AMP icAMP)":"A chemical bond that 	involves sharing of electron pairs.",
    "cyclic 	electron flow":"Infoldings of 	the inner mitochondrial membrane.",
    "cyclic 	photophosphorylation":"A 	second messenger within cells; its formation by adenylate cyclase is 	stimulated by certain hormones or other molecular signals.",
    "cytochromes":"In chloroplasts, the light-induced flow of 	electrons originating from and returning to photosystem I.",
    "cytokinesis":"ATP synthesis driven by cyclic electron 	flow through photosystem I.",
    "cytoplasm":"Heme proteins 	serving as electron carriers in respiration, photosynthesis, and 	other oxidation-reduction reactions.",
    "cytoskeleton":"The final 	separation of daughter cells following mitosis.",
    "cytosol":"The 	portion of a cell's contents outside the nucleus but within the 	plasma membrane; includes organelles such as mitochondria.",
    "dalton":"The filamentous network providing structure 	and organization to the cytoplasm; includes actin filaments, 	microtubules, and intermediate filaments.",
    "dark reactions":"The 	continuous aqueous phase of the cytoplasm, with its dissolved 	solutes; excludes the organelles such as mitochondria.",
    "de novo 	pathway":"The weight of a single hydrogen atom (1.66 x 10 -24g).",
    "deamination":"See carbon fixation reactions.",
    "degenerate 	code":"Pathway for synthesis of a biomolecule, such as a 	nucleotide, from simple precursors; as distinct from a salvage 	pathway.",
    "dehydrogenases":"The enzymatic removal of amino groups 	from biomolecules such as amino acids or nucleotides.",
    "deletion mutation":"A code in which a single element in one language is 	specified by more than one element in a second language.",
    "denaturation":"Enzymes catalyzing the removal of pairs of 	hydrogen atoms from their substrates.",
    "denatured protein":"A 	mutation resulting from the deletion of one or more nucleotides from 	a gene or chromosome.",
    "deoxyribonucleic 	acid":"Partial or complete 	unfolding of the specific native conformation of a polypeptide 	chain, protein, or nucleic acid.",
    "deoxyribonucleotides":"A 	protein that has lost its native conformation by exposure to a 	destabilizing agent such as heat or detergent.",
    "desaturases":"See DNA.",
    "desolvation":"Nucleotides 	containing 2-deoxy-n-ribose as the pentose component.",
    "dextrorotatory isomer":"Enzymes that catalyze the introduction of double bonds into the 	hydrocarbon portion of fatty acids.",
    "diabetes mellitus":"In aqueous 	solution, the release of bound water surrounding a solute.",
    "dialysis":"A stereoisomer that rotates the plane 	of plane-polarized light clockwise.",
    "differential 	centrifugation":"A 	metabolic disease resulting from insulin deficiency; characterized 	by a failure in glucose transport from the blood into cells at 	normal glucose concentrations.",
    "differentiation":"Removal of small 	molecules from a solution of a macromolecule, by allowing them to 	diffuse through a semipermeable membrane into water.",
    "diffusion":"Separation of cell organelles or other 	particles of different size by their different rates of 	sedimentation in a centrifugal field.",
    "digestion":"Specialization of cell structure and function during embryonic 	gnowth and development.",
    "diploid":"The net movement of 	molecules in the direction of lower concentration.",
    "dipole":"Enzymatic hydrolysis of major nutrients in the gastrointestinal 	system to yield their simpler components.",
    "diprotic acid":"Having 	two sets of genetic information; describing a cell with two 	chromosomes of each type.",
    "disaccharide":"A molecule having both 	positive and negative charges.",
    "dissociation constant":"An acid 	having two dissociable protons.",
    "disulfide bridge":"A 	carbohydrate consisting of two covalently joined monosaccharide 	units.",
    "DNA (deoxyribonucleic acid)":"(1) An equilibrium constant 	(Kd) for the dissociation of a 	complex of two or more biomolecules into its components; for 	example, dissociation of a substrate from an enzyme. (2) The 	dissociation constant (Ka) of an 	acid, describing its dissociation into its conjugate base and a 	proton.",
    "DNA chimera":"A covalent cross link between two 	polypeptide chains formed by a cystine residue (two Cys residues).",
    "DNA cloning":"A polynucleotide having a 	specific sequence of deoxyribonucleotide units covalently joined 	through 3',5'-phosphodiester bonds; serves as the carrier of genetic 	informatian.",
    "DNA library":"A DNA containing genetic 	information derived from two different species.",
    "DNA ligase":"See cloning.",
    "DNA looping":"A random collection of cloned 	DNA fragments that includes all or most of the genome of a given 	organism; also called a genomic library.",
    "DNA polymerase":"An 	enzyme that creates a phosphodiester bond between the 3' end of one 	DNA segment and the 5' end of another.",
    "DNA replicase 	system":"The 	interaction of proteins bound at distant sites on a DNA molecule so 	that the intervening DNA forms a loop.",
    "DNA 	transposition":"An 	enzyme that catalyzes template-dependent synthesis of DNA from its 	deoxyribonucleoside 5'-triphosphate precursors.",
    "domain":"The entire complex of enzymes and specialized proteins 	required in biological DNA replication. DNA supercoiling: The 	coiling of DNA upon itself, generally as a result of bending, 	underwinding, or overwinding of the DNA helix.",
    "double 	helix":"See transposition.",
    "double-reciprocal plot":"A distinot 	structural unit of a polypeptide; domains may have separate 	functions and may fold as independent, compact units.",
    "E0'":"The natural coiled conformation of two complementary, 	antiparallel DNA chains.",
    "E. coli (Escherzchia 	coli)":"A plot of 	1/V0 versus I/[S], which allows a 	more accurate determination of Vmax 	and Km, than a plot of Vo versus [S]; 	also called the Lineweaver-Burk plot.",
    "electrochemical 	gradient":"",
    "electrochemical 	potential":"",
    "electrogenic":"See standard reduction potential.",
    "electron acceptor":"A common bacterium found in the small intestine of 	vertehrates; the most well-studied organism.",
    "electron carrier":"The sum of the gradients of concentration and of 	electric charge of an ion across a membrane; the driving force for 	oxidative phosphorylation and photophosphorylation.",
    "electron 	donor":"The energy required to maintain a separation of 	charge and of concentration across a membrane.",
    "electron transfer":"Contributing to an electrical potential across a membrane.",
    "electrophile":"A substance that receives electrons in an 	oxidation-reduction reaction.",
    "electrophoresis":"A protein, 	such as a ilavoprotein or a cytochrome, that can reversibly gain and 	lose electrons; funetions in the transfer of electrons from organic 	nutrients to oxygen or some other terminal acceptor.",
    "elongation factors":"A substance that donates electrons in an 	oxidation-reduction reaction.",
    "eluate":"Movement 	of electrons from substrates to oxygen via the carriers of the 	respiratory (electron transfer) chain.",
    "enantiomers":"An 	electron-deficient group with a strong tendency to accept electrons 	from an electron-rich group (nucleophile).",
    "end-product inhibition":"Movement of charged solutes in response to an electrical field; 	often used to separate mixtures of ions, proteins, or nucleic acids.",
    "endergonic reaetion":"Specific proteins required in the 	elongation of polypeptide chains by ribosomes.",
    "endocrine 	glands":"The 	effluent from a chromatographic column.",
    "endocytosis":"Stereoisomers that are nonsuperimposable mirror images of each 	other.",
    "endonuclease":"See feedback inhibition.",
    "endoplasmic 	reticulum":"A chemical reaction that consumes 	energy (that is, for which ,ΔG is positive).",
    "endothermic reaction":"Groups of cells specialized to synthesize hormones and 	secrete them into the blood to regulate other types of cells.",
    "energy charge":"The uptake of extracellular material by its 	inclusion within a vesicle (endosome) formed by an invagination of 	the plasma membrane.",
    "energy coupling":"An enzyme that 	hydrolyzes the interior phosphodiester bonds of a nucleic acid; that 	is, it acts at points other than the terminal bonds.",
    "enhancers":"An extensive system of double membranes in the 	cytoplasm of eukaryotic cells; it encloses secretory channels and is 	often studded with ribosomes (rough endoplasmic reticulum).",
    "enthalpy (H)":"A chemical reaction that takes up heat 	(that is, for which ΔH is positive).",
    "enthalpy 	change (ΔH)":"The 	fractional degree to which the ATPIADPfAMP system is filled with 	high-energy phosphate groups.",
    "entropy (S)":"The transfer 	of energy from one process to another.",
    "enzyme":"DNA 	sequences that facilitate the expression of a given gene; may be 	located a few hundred, or even thousand, base pairs away from the 	gene.",
    "epimerases":"The heat content of a system.",
    "epimers":"For a reaction, is approximately equal to 	the difference between the energy used to break bonds and the energy 	gained by the formation of new ones.",
    "epithelial cell":"The 	extent of randomness or disorder in a system.",
    "epitope":"A 	biomolecule, either protein or RNA, that catalyzes a specific 	chemical reaction. It does not affect the equilibrium of the 	catalyzed reaction; it enhances the rate of a reaction by providing 	a reaction path with a lower activation energy.",
    "equilibrium":"Enzymes that catalyze the reversible interconversion of two 	epimers.",
    "equilibrium constant (Keq)":"Two stereoisomers differing in 	configuration at one asymmetric center, in a compound having two or 	more asymmetric ceuters.",
    "erythrocyte":"Any cell that 	forms part of the outer covering of an organism or organ.",
    "Escherichia coli":"An antigenic determinant; the particular chemical group or 	groups within a macromolecule (antigen) to which a given antibody 	binds.",
    "essential amino acids":"The state of a system in which no 	further net change is occurring; the free energy is at a minimum.",
    "essential fatty acids":"",
    "ethanol fermentation":"",
    "eukaryote":"A constant, characteristic for each chemical reaction; relates 	the specific concentrations of all reactants and products at 	equilibrium at a given temperature and pressure.",
    "excited state":"A 	cell containing large amounts of hemoglobin and specialized for 	oxygen transport; a red blood cell.",
    "exergonic reaction":"See 	E. coli.",
    "exocytosis":"Amino acids that cannot be 	synthesized by humans (and other vertebrates) and must be obtained 	from the diet.",
    "exon":"The group of 	polyunsaturated fatty acids produced by plants, but not by humans; 	required in the human diet.",
    "exonuclease":"See 	alcohol fermentation.",
    "exothermic 	reaction":"A unicellular or 	multicellular organism with cells having a membranebounded nucleus, 	multiple chromosomes, and internal organelles.",
    "expression vector":"An energy-rich state of an atom or molecule; produced by the 	absorption of light energy.",
    "facilitated diffusion":"A chemical 	reaction that proceeds with the release of free energy (that is, for 	which ΔG is negative).",
    "facultative 	cells":"The fusion of an 	intracellular vesicle with the plasma membrane, releasing the 	vesicle contents to the extracellular space.",
    "FAD (flavin adenine dinucleotide)":"The 	segment of a eukaryotic gene that encodes a portion of the final 	product of the gene; a portion that remains after 	posttranscriptional processing and is transcribed into a protein or 	incorporated into the structure of an RNA. See intron.",
    "fatty 	acid":"An enzyme that hydrolyzes only those phosphodiester bonds that 	are in the terminal positions of a nucleic acid.",
    "feedback inhibition":"A chemical reaction that releases heat (that is, for 	which ΔH is negative).",
    "fermentation":"See vector.",
    "fibroblast":"Diffusion of a polar substance 	across a biological membrane through a protein transporter; also 	called passive diffusion or passive transport.",
    "fibrous proteins":"Cells that can live in the presence or absence of 	oxygen.",
    "fingerprinting":"The coenzyme of 	some oxidation-reduction enzymes; it contains riboflavin.",
    "first 	law of thermodynamics":"A long-chain aliphatic carboxylic acid found in natural 	fats and oils; also a component of membrane phospholipids and 	glycolipids.",
    "Fischer 	projection formulas":"Inhibition of an 	allosteric enzyme at the beginning of a metabolic sequence by the 	end product of the sequence; also known as end-product inhibition.",
    "5' end":"Energy-yielding anaerobic breakdown of a 	nutrient molecule, such as glucose, without net oxidation; yields 	lactate, ethanol, or some other simple product.",
    "flagellum":"A 	cell of the connective tissue that secretes connective tissue 	proteins such as collagen.",
    "flavin-linked dehydrogenases":"Insoluble 	proteins that serve in a protective or structural role; contain 	polypeptide chains that generally share a common secondary 	structure.",
    "flavin nucleotides":"See peptide mapping.",
    "flavoprotein":"The law stating that in all processes, 	the total energy of the universe remains constant.",
    "fluid mosaic model":"See projection formulas.",
    "fluorescence":"The 	end of a nucleic acid that lacks a nucleotide bound at the 5' 	position of the terminal residue.",
    "FMN 	(flavin mononucleotide)":"A cell 	appendage used in propulsion. Bacterial flagella have a much simpler 	structure than eukaryotic flagella, which are similar to cilia.",
    "footprinting":"Dehydrogenases requiring one 	of the riboflavin coenzymes, FMN or FAD.",
    "frame shift":"Nucleotide coenzymes (FMN and FAD) containing riboflavin.",
    "free energy (G)":"An enzyme containing a flavin nucleotide as a 	tightly bound prosthetic group.",
    "free energy of activation (ΔG#) 	See activation energy.  free-energy change (ΔG)":"A model 	describing biological membranes as a fluid lipid bilayer with 	embedded proteins; the bilayer exhibits both structural and 	functional asymmetry.",
    "free radical":"Emission of light by 	excited molecules as they revert to the ground state.",
    "functional group":"Riboflavin phosphate, a coenzyme of 	certain oxidation-reduction enzymes.",
    "furanose":"A 	technique for identifying the nucleic acid sequence bound by a DNA- 	or RNA-binding protein.",
    "fusion protein":"A mutation caused by 	insertion or deletion of one or more paired nucleotides, changing 	the reading frame of codons during protein synthesis; the 	polypeptide product has a garbled amino acid sequence beginning at 	the mutated codon.",
    "futile cycle":"The component of the 	total energy of a system that can do work at constant temperature 	and pressure.",
    "ΔG°'":"",
    "gametes":"",
    "gangliosides":"See activation energy.",
    "gel flltration":"The 	amount of free energy released (negative ΔG) or absorbed 	(positive ΔG) in a reaction at constant temperature and 	pressure.",
    "gene":"See radical.",
    "gene expression":"The specific atom or group of atoms that confers a particular 	chemical property on a biomolecule.",
    "gene splicing":"A simple 	sugar containing the five-membered furan ring.",
    "general acid-base catalysis":"(1) A family of proteins that facilitate membrane fusion. (2) 	The protein product of a gene created by the fusion of two distinct 	genes.",
    "genetic 	code":"A set of enzyme-catalyzed cyclic 	reactions that results in release of thermal energy by the 	hydrolysis of ATP.",
    "genetic information":"See standard free-energy 	change.",
    "genetic map":"Reproductive cells with a haploid gene 	content; sperm or egg cells.",
    "genome":"Sphingolipids, 	containing complex oligosaccharides as head groups; especially 	common in nervous tissue.",
    "genotype":"A chromatographic 	procedure for the separation of a mixture of molecules on the basis 	of size; based on the capacity of porous polymers to exclude solutes 	above a certain size.",
    "geometric isomers":"A chromosomal segment that 	codes for a single functional polypeptide chain or RNA molecule.",
    "germ-line 	cell":"lYanscription and, in the case of proteins, 	translation to yield the product of a gene; a gene is expressed when 	its biological product is present and active.",
    "globular proteins":"The enzymatic attachment of one gene, or part of a gene, to 	another.",
    "glucogenic amino acids":"Catalysis involving 	proton transfer(s) to or from a molecule other than water.",
    "gluconeogenesis":"The set of triplet code words in DNA (or mRNA) coding for 	the amino acids of proteins.",
    "glycan":"The 	hereditary information contained in a sequence of nucleotide bases 	in chromosomal DNA or RNA.",
    "glycerophospholipid":"A diagram showirg 	the relative sequence and position of specific genes along a 	chromosome.",
    "glycolipid":"All the genetic information encoded in 	a cell or virus.",
    "glycolysis":"The genetic constitution of an 	organism, as distinct from its physical characteristics, or 	phenotype.",
    "glycoprotein":"Isomers related by rotation 	about a double bond; also called cis and trans isomers.",
    "glycosaminoglycan":"A type of animal cell that is formed early in 	embryogenesis and may multiply by mitosis or may produce, by 	meiosis, cells that develop into gametes (egg or sperm cells).",
    "glycosidic bonds":"Soluble proteins with a globular 	(somewhat rounded) shape.",
    "glyoxylate cycle":"Amino 	acids with carbon chains that can be metabolically converted into 	glucose or glycogen via gluconeogenesis.",
    "glyoxysome":"The 	biosynthesis of a carbohydrate from simpler, noncarbohydrate 	precursors such as oxaloacetate or pyruvate.",
    "Golgi complex":"Another 	term for polysaccharide; a polymer of monosaccharide units joined by 	glycosidic bonds.",
    "gram molecular weight":"An amphipathic lipid 	with a glycerol backbone; fatty acids are ester-linked to Gl and C-2 	of glycerol, and a polar alcohol is attached through a 	phosphodiester linkage to C-3.",
    "grana":"A lipid 	containing a carbohydrate group.",
    "ground state":"The catabolic 	pathway by which a molecule of glucose is broken down into two 	molecules of pyruvate.",
    "group transfer potential":"A protein containing a 	carbohydrate group.",
    "half-life":"A 	heteropolysaccharide of two alternating units: one is either 	N-acetylglucosamine or N-acetylgalactosamine; the other is a uronic 	acid (usually glucuronic acid). Formerly called mucopolysaccharide.",
    "haploid":"Bonds between a sugar and another molecule 	(typically an alcohol, purine, pyrimidine, or sugar) through an 	intervening oxygen or nitrogen atom; the bonds are classified as 	O-glycosidic or N-glycosidic, respectively.",
    "Haworth 	perspective formulas":"A 	variant of the citric acid cycle, for the net conversion of acetate 	into succinate and, eventually, new some",
    "helicase":"A 	specialized peroxisome containing the enzymes of the glyoxylate 	cycle; found in cells of germinating seeds.",
    "helix, α":"A 	complex membranous organelle of eukaryotic cells; functions in the 	posttranslational modification of proteins and their secretion from 	the cell or incorporation into the plasma membrane or organellar 	membranes.",
    "heme":"The weight in grams of a 	compound that is numerically equal to its molecular weight; the 	weight of 1 mole.",
    "heme protein":"Stacks of thylakoids, flattened 	membranous sacs or discs, in chloroplasts.",
    "hemoglobin":"The 	normal, stable form of an atom or molecule; as distinct from the 	excited state.",
    "Henderson-Hasselbalch 	equation":"A measure of the 	ability of a compound to donate an activated group (such as a 	phosphate or acyl group); generally expressed as the standard free 	energy of hydrolysis.",
    "hepatocyte":"The time required for the 	disappearance or decay of one-half of a given component in a system.",
    "heteroduplex DNA":"Having a single set of genetic information; 	describing a cell with one chromosome of each type.",
    "similar sequences, 	often as a product of genetic recombination. heteropolysaccharide":"A method for representing cyclic chemical 	structures so as to define the configuration of each substituent 	group; the method commonly used for representing sugars.",
    "heterotroph":"An enzyme that catalyzes the separation of strands in a DNA 	molecule before replication.",
    "heterotropic enzyme":"See α 	helix.",
    "hexose":"The iron-porphyrin prosthetic group of heme 	proteins.",
    "high-performance liquid 	chromatography (HPLC)":"A protein containing a heme as a 	prosthetic group.",
    "Hill 	reaction":"A heme protein in 	erythrocytes; functions in oxygen transport.",
    "histones":"An equation relating the pH, the pKa, 	and the ratio of the concentrations of the protonacceptor (A-) 	and proton-donor (HA) species in a solution.",
    "Holliday intermediate":"The 	major cell type of liver tissue.",
    "holoenzyme":"Duplex 	DNA containing complementary strands derived",
    "homeobox":"A polysaccharide containing more than one type of sugar.",
    "homeodomain":"An organism that requires complex nutrient 	molecules, such as glucose, as a source of energy and carbon.",
    "homeostasis":"An allosteric enzyme requiring a 	modulator other than its substrate.",
    "homeotic genes":"A simple sugar 	with a backbone containing six carbon atoms. high-energy compound: A 	compound that on hydrolysis undergoes a large decrease in free 	energy under standard conditions.",
    "homologous genetic recombination":"Chromatographic procedures, often 	conducted at relatively high pressures, using automated equipment 	that permits refined and highly reproducible profiles.",
    "homelogous proteins":"The evolution of oxygen and the photoreduction of an 	artificial electron acceptor by a chloroplast preparation in the 	absence of carbon dioxide.",
    "homotropic enzyme":"The family of five 	basic proteins that associate tightly with DNA in the chromosomes of 	all eukaryotic cells.",
    "hormone":"An 	intermediate in genetic recombination in which two double-stranded 	DNA molecules are joined by virtue of a reciprocal crossover 	involving one strand of each molecule.",
    "hormone receptor":"A 	catalytically active enzyme including all necessary subunits, 	prosthetic groups, and cofactors.",
    "hydrogen bond":"A conserved DNA 	sequence of 180 base pairs encoding a protein domain found in many 	proteins that play a regulatory role in development.",
    "hydrolases":"The protein domain encoded by the homeobox.",
    "hydrolysis":"The maintenance of a dynamic steady state by regulatory 	mechanisms that compensate for changes in external circumstances.",
    "hydronium ion":"Genes that regulate the development of the 	pattern of segments in the Drosophila body plan; similar genes are 	found in most vertebrates.",
    "hydropathy index":"Recombination between two DNA molecules of similar sequence, 	occurring in all cells; occurs during meiosis and mitosis in 	eukaryotes.",
    "hydrophilic":"Proteins having sequences 	and functions similar in difierent species; for example, the 	hemoglobins. made up ride unit.",
    "hydrophobic":"An 	allosteric enzyme that uses its substrate as a modulator.",
    "hydrophobic interactions":"A chemical substance synthesized in small amounts by an 	endocrine tissue and carried in the blood to another tissue, where 	it acts as a messenger to regulate the function of the target tissue 	or organ.",
    "hyperchromic effect":"A protein in, or on the surface 	of, target cells that binds a specific hormone and initiates the 	cellular response.",
    "immune response":"A weak electrostatic 	attraction between one electronegative atom (such as oxygen or 	nitrogen) and a hydrogen atom covalently linked to a second 	electronegative atom.",
    "immunoglobulin":"Enzymes (proteases, 	lipases, phosphatases, nucleases, for example) that catalyze 	hydrolysis reactions.",
    "in vitro":"Cleavage of a bond, such 	as an anhydride or peptide bond, by the addition of the elements of 	water, yielding two or more products.",
    "in vivo":"The 	hydrated hydrogen ion (H2O+).",
    "induced fit":"A scale that expresses the relative 	hydrophobic and hydrophilic tendencies of a chemical group.",
    "inducer":"Polar or charged; describing molecules or 	groups that associate with (dissolve easily in) water.",
    "induction":"Nonpolar; describing molecules or groups that are insoluble in 	water.",
    "informational macromolecules":"The association of 	nonpolar groups, or compounds, with each other in aqueous systems, 	driven by the tendency of the surrounding water molecules to seek 	their most stable (disordered) state.",
    "initiation codon":"The 	large increase in light absorption at 260 nm occurring as a 	double-helical DNA is melted (unwound).",
    "initiation complex":"The 	capacity of a vertebrate to generate antibodies to an antigen, a 	macromolecule foreign to the organism.",
    "inorganic pyrophosphatase":"An 	antibody protein generated against, and capable of binding 	specifically to, an antigen.",
    "insertion mutation":""In glass"; 	that is, in the test tube.",
    "insertion sequence":""In life"; 	that is, in the living cell or organism.",
    "integral membrane proteins":"A 	change in the conformation of an enzyme in response to substrate 	binding that renders the enzyme catalytically active; also used to 	denote changes in the conformation of any macromolecule in response 	to ligand binding such that the binding site of the macromolecule 	better conforms to the shape of the ligand.",
    "intercalating mutagen":"A 	signal molecule that, when bound to a regulatory protein, produces 	an increase in the expression of a given gene.",
    "intercalation":"An 	increase in the expression of a gene in response to a change in the 	activity of a regulatory protein.",
    "interferons":"Biomolecules containing information in the form of specific 	sequences of different monomers; for example, many proteins, lipids, 	polysaccharides, and nucleic acids.",
    "intermediary 	metabolism":"AUG 	(sometimes GUG in prokaryotes); codes for the first amino acid in a 	polypeptide sequence: N-formylmethionine in prokaryotes, and 	methionine in eukaryotes.",
    "intron (intervening 	sequence)":"A complex of 	a ribosome with an mRNA and the initiating Met-tRNAMet 	or fMet-tRNAfMet, ready for the 	elongation steps.",
    "ion 	channel":"An enzyme that 	hydrolyzes a molecule of inorganic pyrophosphate to yield two 	molecules of (ortho) phosphate; also known as pyrophosphatase.",
    "ion-exchange resin":"A mutation caused by insertion of one or 	more extra bases, or a mutagen, between two successive bases in DNA.",
    "ion product of water (Kw)":"Specific base sequences at either end 	of a transposable segment of DNA.",
    "ionizing 	radiation":"Proteins firmly bound to a membrane by hydrophobic interactions; 	as distinct from peripheral proteins.",
    "ionophore":"A 	mutagen that inserts itself between two successive bases in a 	nucleic acid, causing a frame-shift mutation.",
    "iron-sulfur center":"Insertion between two stacked aromatic or planar rings; for 	example, the insertion of a planar molecule between two successive 	bases in a nucleic acid.",
    "isoelectric focusing":"A class of 	glycoproteins with antiviral activities.",
    "isoelectric pH (isoelectric point)":"In cells, the enzyme-catalyzed reactions that 	extract chemical energy from nutrient molecules and utilize it to 	synthesize and assemble cell components.",
    "isoenzymes":"A sequence of nucleotides in a gene that is 	transcribed but excised before the gene is translated.",
    "isomerases":"An integral membrane protein that provides for the 	regulated transport of a specific ion, or ions, across a membrane.",
    "isomers":"A polymeric resin that contains fixed 	charged groups; used in chromatographic columns to separate ionic 	compounds.",
    "isoprene":"The product of the 	concentrations of H+ and OH- 	in pure water: KW = [H+][OH-] 	= 1 x 10-14 at 25 °C.",
    "isothermal":"A type of radiation, such as x rays, that causes 	loss of electrons from some organic molecules, thus making them more 	reactive.",
    "isotopes":"A compound that binds one or more 	metal ions and is capable of dif fusing across a membrane, carrying 	the bound ion.",
    "isozymes":"A prosthetic group of 	certain redox proteins involved in electron transfers; Fe2+ 	or Fe3+ is bound to inorganic sulfur 	and to Cys groups in the protein.",
    "keratins":"An 	electrophoretic method for separating macromolecules on the basis of 	their isoelectric pH.",
    "ketogenic amino acids":"The 	pH at which a solute has no net electric charge and thus does not 	move in an electric field.",
    "ketone bodies":"See isozymes.",
    "ketose":"Enzymes that catalyze the transformation of 	compounds into their positional isomers.",
    "ketosis":"Any two 	molecules with the same molecular formula but a different 	arrangement of molecular groups.",
    "kinases":"The hydrocarbon 	2-methyl-1,3-butadiene, a recurring structural unit of the terpenoid 	biomolecules.",
    "kinetics":"Occurring at constant 	temperature.",
    "Krebs cycle":"Stable or radioactive forms of an 	element that differ in atomic weight but are otherwise chemically 	identical to the naturally abundant form of the element; used as 	tracers.",
    "lagging strand":"Multiple forms of an enzyme that 	catalyze the same reaction but differ from each other in their amino 	acid sequence, substrate affinity, Vmax, 	and/or regulatory properties; also called isoenzymes.",
    "law of mass action":"Insoluble protective or structural proteins consisting of 	parallel polypeptide chains in α-helical or β 	conformations.",
    "leader":"Amino acids with 	carbon skeletons that can serve as precursors of the ketone bodies.",
    "leading strand":"Acetoacetate, D-βhydroxybutyrate, and 	acetone; watersoluble fuels normally exported by the liver but 	overproduced during fasting or in untreated diabetes mellitus.",
    "leaky mutant":"A simple monosaccharide in which the carbonyl group 	is a ketone.",
    "leaving group":"A condition in which the 	concentration of ketone bodies in the blood, tissues, and urine is 	abnormally high.",
    "lethal mutation":"Enzymes that catalyze the 	phosphorylation of certain molecules by ATP.",
    "leucine zipper":"The 	study of reaction rates.",
    "leukotrienes":"See citric acid 	cycle.",
    "levorotatory isomer":"The DNA strand that, during 	replication, must be synthesized in the direction opposite to that 	in which the replication fork moves.",
    "ligand":"The 	law stating that the rate of any given chemical reaction is 	proportional to the product of the activities (or concentrations) of 	the reactants.",
    "light 	reactions":"A short sequence near the amino 	terminus of a protein or the 5' end of an RNA that has a specialized 	targeting or regulatory function.",
    "Lineweaver-Burk equation":"The DNA 	strand that, during replication, is synthesized in the same 	direction in which the replication fork moves.",
    "linking number":"A 	mutant gene that gives rise to a product with a detectable Ievel of 	biological activity.",
    "lipases":"The departing or 	displaced molecular group in a unimolecular elimination or a 	bimolecular substitution reaction.",
    "lipid":"A 	mutation that inactivates a biological funetion essential to the 	life of the cell or organism.",
    "lipoate 	(lipoic acid)":"A protein 	structural motif involved in protein-protein interactions in many 	eukaryotic regulatory proteins; consists of two interacting α 	helices in which Leu residues in every seventh position are a 	prominent feature of the interacting surfaces.",
    "lipoprotein":"A 	family of molecules derived from arachidonate; muscle contractants 	that constrict air passages in the lungs and are involved in asthma.",
    "low-energy 	phosphate compound":"A stereoisomer that rotates the plane 	of plane-polarized light counterclockwise.",
    "lyases":"A small 	molecule that binds specifically to a larger one; for example, a 	hormone is the ligand for its specific protein receptor.",
    "lymphocytes":"The reactions of photosynthesis that require light 	and cannot occur in the dark; also known as the light-dependent 	reactions.",
    "lysis":"An algebraic transform 	of the Michaelis-Menten equation, allowing determination of Vmax 	and Km by extrapolation of [S] to 	infinity.",
    "lysogeny":"The number of times one closed 	circular DNA strand is wound about another; the number of 	topological links holding the circles together.",
    "lysosome":"Enzymes that catalyze the hydrolysis of triacylglycerols.",
    "macromolecule":"A small water-insoluble biomolecule generally 	containing fatty acids, sterols, or isoprenoid compounds.",
    "mass-action ratio":"A vitamin for some microorganisms; an 	intermediate carrier of hydrogen atoms and acyl groups in α-keto 	acid dehydrogenases.",
    "matrix":"A lipid-protein aggregate 	that serves to carry water-insoluble lipids in the blood. The 	protein component alone is an apolipoprotein.",
    "meiosis":"A phosphorylated compound with a relatively 	small standard free energy of hydrolysis.",
    "membrane transport":"Enzymes 	that catalyze the removal of a group from a molecule to form a 	double bond, or the addition of a group to a double bond.",
    "messenger RNA (mRNA)":"A subclass of leukocytes involved in the immune 	response. B lymphocytes synthesize and secrete antibodies; T 	lymphocytes either play a regulatory role in immunity or kill 	foreign and virus-infected cells.",
    "metabolism":"Destruction of a 	cell's plasma membrane or of a bacterial cell wall, releasing the 	cellular contents and killing the cell.",
    "metabolite":"One of 	two outcomes of the infection of a host cell by a temperate phage. 	It occurs when the phage genome becomes repressed and is replicated 	as part of the host DNA; infrequently it may be induced, and the 	phage particles so produced cause the host cell to lyse.",
    "metalloprotein":"A membrane-bounded organelle in the cytoplasm of eukaryotic 	cells; it contains many hydrolytic enzymes and serves as a degrading 	and recycling center for unneeded components.",
    "metamerism":"A 	molecule having a molecular weight in the range of a few thousand to 	many millions.",
    "micelle":"For the reaction aA + dB 	 	cC + dD, the ratio:  	[C]c[D]d,
    "Michaelis-Menten constant (Km)":"The aqueous contents of a cell or organelle (the 	mitochondrion, for example) with dissolved solutes.",
    "Michaelis-Menten 	equation":"A 	type of cell division in which diploid cells give rise to haploid 	cells destined to become gametes.",
    "Michaelis-Menten kinetics":"Movement 	of a polar solute across a membrane via a specific membrane protein 	(a transporter).",
    "microbodies":"A class of RNA 	molecules, each of which is complementary to one strand of DNA; 	carries the genetic message from the chromosome to the ribosomes.",
    "microfilaments":"The entire set of enzymecatalyzed 	transformations of organic molecules in living cells; the sum of 	anabolism and catabolism.",
    "microsomes":"A chemical 	intermediate in the enzyme-catalyzed reactions of metabolism.",
    "microtubules":"A protein having a metal ion as its 	prosthetic group.",
    "mitochondrion":"Division of the body into 	segments; in insects, for example.",
    "mitosis":"An aggregate of 	amphipathic molecules in water, with the nonpolar portions in the 	interior and the polar portions at the exterior surface, exposed to 	water.",
    "mixed-function oxidases (oxygenases)":"",
    "modulator":"",
    "molar solution":"The substrate concentration at which an enzyme-catalyzed 	reaction proceeds at onehalf its maximum velocity.",
    "mole":"The equation describing the hyperbolic dependence of 	the initial reaction velocity, V0, on 	substrate concentration, [S], in many enzymecatalyzed reactions:  	</dt></dl> <center> <table cellpadding="2" cellspacing="2"> <tr> <td rowspan="2"> <p>V0 =",
    "monoclonal antibodies":"A kinetic pattern in which the 	initial rate of an enzyme-catalyzed reaction exhibits a hyperbolic 	dependence on substrate concentration.",
    "monolayer":"Cytoplasmic, membranebounded vesicles containing peroxideforming 	and peroxide-destroying enzymes; include lysosomes, peroxisomes, and 	glyoxysomes.",
    "monoprotic acid":"Thin filaments composed of 	actin, found in the cytoplasm of eukaryotic cells; serve in 	structure and movement.",
    "monosaccharide":"Membranous vesicles 	formed by fragmentation of the endoplasmic reticulum of eukaryotic 	cells; recovered by differential centrifugation.",
    "mRNA":"Thin tubules assembled from two types of globular tubulin 	subunits; present in cilia, flagella, centrosomes, and other 	contractile or motile structures.",
    "mucopolysaccharide":"Membrane-bounded organelle in the cytoplasm of eukaryotes; 	contains the enzyme systems required for the citric acid cycle, 	fatty acid oxidation, electron transfer, and oxidative 	phosphorylation.",
    "multienzyme system":"The multistep process in 	eukaryotic cells that results in the replication of chromosomes and 	cell division.",
    "mutarotation":"Enzymes, 	often flavoproteins, that use molecular oxygen (O2) 	to simultaneously oxidize a substrate and a cosubstrate (commonly 	NADH or NADPH).",
    "mutases":"A metabolite that, when bound to 	the allosteric site of an enzyme, alters its kinetic 	characteristics.",
    "mutation":"One mole of solute 	dissolved in water to give a total volume of 1,000 mL.",
    "myofibril":"One gram molecular weight of a compound. See Avogadro's number.",
    "myosin":"Antibodies produced by a cloned 	hybridoma cell, which therefore are identical and directed against 	the same epitope of the antigen.",
    "NAD, NADP (nicotinamide adenine dinucleotide, nicotinamide 	adenine dinucleotide phosphate)":"A single layer 	of oriented lipid molecules.",
    "native conformation":"An acid 	having only one dissociable proton.",
    "negative 	cooperativity":"A 	carbohydrate consisting of a single sugar unit.",
    "negative feedback":"See 	messenger RNA.",
    "neuron":"An older name for a 	glycosaminoglycan.",
    "neurotransmitter":"A group of related 	enzymes participating in a given metabolic pathway.",
    "nicotinamide adenine dinucleotide, 	nicotinamide adenine dinucleotide phosphate":"The change in specific rotation of a pyranose or furanose sugar 	or glycoside accompanying the equilibration of its α- and 	β-anomeric forms.",
    "ninhydrin reaetion":"Enzymes that catalyze the 	transposition of functional groups.",
    "nitrogen cycle":"An 	inheritable change in the nucleotide sequence of a chromosome.",
    "nitrogen fixation":"A unit of thick and thin filaments of muscle 	fibers.",
    "nitrogenase complex":"A contractile protein; the major component 	of the thick filaments of muscle and other actin-myosin systems.",
    "noncompetitive inhibition":"Nicotinamide-containing 	coenzymes functioning as carriers of hydrogen atoms and electrons in 	some oxidation-reduction reactions.",
    "noncyclic 	electron flow":"The 	biologically active conformation of a macromolecule.",
    "nonessential amino acids":"A phenomenon of some multisubunit enzymes or 	proteins in which binding of a ligand or substrate to one subunit 	impairs binding to another subunit.",
    "nonheme iron proteins":"Regulation of a biochemical pathway achieved when a reaction 	product inhibits an earlier step in the pathway.",
    "nonpolar":"A 	cell of nervous tissue specialized for transmission of a nerve 	impulse.",
    "nonsense 	codon":"A low molecular weight compound 	(usually containing nitrogen) secreted from the terminal of a neuron 	and bound by a specific receptor in the next neuron; serves to 	transmit a nerve impulse.",
    "nonsense mutation":"See NAD, NADP.",
    "nonsense suppressor":"A color reaction given by amino acids 	and peptides on heating with ninhydrin; widely used for their 	detection and estimation.",
    "nucleases":"The cycling of 	various forms of biologically available nitrogen through the plant, 	animal, and microbial worlds, and through the atmosphere and 	geosphere.",
    "nucleic acids":"Conversion of atmospheric 	nitrogen (N2) into a reduced, 	biologically available form by nitrogen-fixing organisms.",
    "nucleoid":"A system of enzymes capable of reducing 	atmospheric nitrogen to ammonia in the presence of ATP.",
    "nucleolus":"A type of enzyme inhibition not 	reversed by increasing the substrate concentration.",
    "nucleophile":"The lightinduced flow of electrons from water to 	NADP+ in oxygen-evolving 	photosynthesis; it involves both photosystems I and II.",
    "nucleoplasm":"Amino acids that can be made by 	humans and other vertebrates from simpler precursors, and are thus 	not required in the diet.",
    "nucleoside":"Proteins, 	usually acting in oxidation-reduction reactions, containing iron but 	no porphyrin groups.",
    "nucleoside diphosphate kinase":"Hydrophobic; describing 	molecules or groups that are poorly soluble in water.",
    "nucleoside diphosphate sugar":"A codon that does not specify an amino acid, but signals 	the termination of a polypeptide chain.",
    "nucleoside monophosphate 	kinase":"A 	mutation that results in the premature termination of a polypeptide 	chain.",
    "nucleosome":"A mutation, usually in the gene 	for a tRNA, that causes an amino acid to be inserted into a 	polypeptide in response to a termination codon.",
    "nucleotide":"Enzymes that hydrolyze the internucleotide (phosphodiester) 	linkages of nucleic acids.",
    "nucleus":"Biologically 	occurring polynucleotides in which the nucleotide residues are 	linked in a specific sequence by phosphodiester bonds; DNA and RNA.",
    "oligomer":"In bacteria, the nuclear zone that contains the 	chromosome but has no surrounding membrane.",
    "oligomeric protein":"A 	densely staining structure in the nucleus of eukaryotic cells; 	involved in rRNA synthesis and ribosome formation.",
    "oligonucleotide":"An electron-rich group with a strong tendency to donate 	electrons to an electron-deficient nucleus (electrophile); the 	entering reactant in a bimolecular substitution reaction.",
    "oligopeptide":"The portion of a cell's contents enclosed by 	the nuclear membrane; ' also called the nuclear matrix.",
    "oligosaccharide":"A compound consisting of a purine or pyrimidine base covalently 	linked to a pentose.",
    "oncogene":"An 	enzyme that catalyzes the transfer of the terminal phosphate of a 	nucleoside 5'-triphosphate to a nucleoside 5'-diphosphate.",
    "open reading frame":"A coenzymelike carrier of a 	sugar molecule, functioning in the enzymatic synthesis of 	polysaccharides and sugar derivatives.",
    "open system":"An enzyme that catalyzes the transfer of the terminal 	phosphate of ATP to a nucleoside 5'-monophosphate.",
    "operator":"Structural unit for packaging chromatin; consists of a DNA 	strand wound around a histone core.",
    "operon":"A 	nucleoside phosphorylated at one of its pentose hydroxyl groups.",
    "optical activity":"In eukaryotes, a membranebounded organelle that 	contains chromosomes.",
    "optimum pH":"A short polymer, usually of 	amino acids, sugars, or nucleotides; the definition of 'short' 	is somewhat arbitrary, but usually less than 50 subunits.",
    "organelles":"A multisubunit protein having two or 	more identical polypeptide chains.",
    "origin":"A short 	polymer of nucleotides (usually less than 50).",
    "osmosis":"A 	few amino acids joined by peptide bonds.",
    "osmotic pressure":"Several monosaccharide groups joined by glycosidic bonds.",
    "oxidation":"A cancer-causing gene; any af several mutant genes 	that cause cells to exhibit rapid, uncontrolled proliferation. See 	also proto-oncogene.",
    "oxidation, β":"A group of 	contiguous nonoverlapping nucleotide codons in a DNA or RNA molecule 	that do not include a termination codon.",
    "oxidation-reduction reaction":"A 	system that exchanges matter and energy with its surroundings. See 	also system.",
    "oxidative phosphorylation":"A region of DNA that interacts with 	a repressor protein to control the expression of a gene or group of 	genes.",
    "oxidizing agent (oxidant)":"A unit of genetic expression consisting of 	one or more related genes and the operator and promoter sequences 	that regulate their transcription.",
    "oxygen 	debt":"The 	capacity of a substance to rotate the plane of plane-polarized 	light.",
    "oxygenases":"The characteristic pH at which an enzyme 	has maximal catalytic activity.",
    "palindrome":"Membrane-bounded 	structures found in eukaryotic cells; contain enzymes and other 	components required for specialized cell functions.",
    "paradigm":"The 	nucleotide sequence or site in DNA where DNA replication is 	initiated.",
    "partition 	coefficient":"Bulk flow of water through a 	semipermeable membrane into another aqueous compartment containing 	solute at a higher concentration.",
    "pathogenic":"Pressure 	generated by the osmotic flow of water through a semipermeable 	membrane into an aqueous compartment containing solute at a higher 	concentration.",
    "pentose":"The loss of electrons from a 	compound.",
    "pentose phosphate pathway":"See β oxidation.",
    "peptidase":"A reaction in which electrons 	are transferred from a donor to an acceptor molecule; also called a 	redox reaction.",
    "peptide":"The enzymatic 	phosphorylation of ADP to ATP coupled to electron transfer from a 	substrate to molecular oxygen.",
    "peptide bond":"The 	acceptor of electrons in an oxidation-reduction reaction.",
    "peptide mapping":"The extra oxygen (above the normal resting level) 	consumed in the recovery period after strenuous physical exertion.",
    "peptidoglycan":"Enzymes that catalyze reactions in which oxygen 	is introduced into an acceptor molecule.",
    "peripheral 	proteins":"A 	segment of duplex DNA in which the base sequences of the two strands 	exhibit twofold rotational symmetry about an axis.",
    "permeases":"In 	biochemistry, an experimental model or example.",
    "pH":"A constant that expresses the ratio in which a 	given solute will be partitioned or distributed between two given 	immiscible liquids at equilibrium.",
    "phage":"Disease-causing.",
    "phenotype":"A simple sugar with a backbone containing five 	carbon atoms.",
    "phosphodiester linkage":"A pathway that 	serves to interconvert hexoses and pentoses and is a source of 	reducing equivalents and pentoses for biosynthetic processes; 	present in most organisms. Also called the phosphogluconate pathway.",
    "phosphogluconate pathway":"An enzyme that hydrolyzes a peptide bond.",
    "phospholipid":"Two or more amino acids covalently joined by 	peptide bonds.",
    "phosphorolysis":"A substituted amide linkage 	between the α-amino group of one amino acid and the α-carboxyl 	group of another, with the elimination of the elements of water.",
    "phosphorylation":"The characteristic two-dimensional pattern 	(on paper or gel) formed by the separation of a mixture of peptides 	resulting from partial hydrolysis of a protein; also known as 	peptide fingerprinting.",
    "phosphorylation potential (ΔGp)":"A major component of 	bacterial cell walls; generally consists of parallel 	heteropolysaccharides cross-linked by short peptides.",
    "photochemical 	reaction center":"Proteins that are loosely or reversibly bound to a 	membrane by hydrogen bonds or electrostatic forces; generally 	water-soluble once released from the membrane.",
    "photon":"See 	transporters. peroxisome: Membrane-bounded organelle in the 	cytoplasm of eukaryotic cells; contains peroxide-forming and 	peroxidedestroying enzymes.",
    "photophosphorylation":"The negative logarithm of 	the hydrogen ion concentration of an aqueous solution.",
    "photoreduction":"See bacteriophage.",
    "photorespiration":"The observable 	characteristics of an organism.",
    "photosynthesis":"A 	chemical grouping that contains two alcohols esterified to one 	molecule of phosphoric acid, which thus serves as a bridge between 	them.",
    "photosynthetic phosphorylation":"An oxidative pathway 	beginning with glucose-6phosphate and leading, via 	6-phosphogluconate, to pentose phosphates and yielding NADPH. Also 	called the pentose phosphate pathway.",
    "photosystem":"A lipid 	containing one or more phosphate groups.",
    "phototroph":"Cleavage of a compound with phosphate as the attacking group; 	analogous to hydrolysis.",
    "pK":"Formation of a 	phosphate derivative of a biomolecule, usually 6y enzymatic transfer 	of a phosphate group from ATP.",
    "plasma membrane":"",
    "plasma proteins":"",
    "plasmalogen":"The actual free-energy change of ATP hydrolysis under the 	nonstandard conditions prevailing within a cell.",
    "plasmid":"The part of a photosynthetic complex where the 	energy of an absorbed photon causes charge separation, initiating 	electron transfer.",
    "plastid":"The ultimate unit (a quantum) of 	light energy.",
    "platelets":"The enzymatic formation 	of ATP from ADP coupled to the light-dependent transfer of electrons 	in photosynthetic cells.",
    "pleated sheet":"The light-induced 	reduction of an electron acceptor in photosynthetic cells.",
    "polar":"Oxygen consumption occurring in 	illuminated temperate-zone plants, largely due to oxidation of 	phosphoglycolate.",
    "polarity":"The use of light energy 	to produce carbohydrates from carbon dioxide and a reducing agent 	such as water.",
    "polyclonal 	antibodies":"See 	photophosphorylation.",
    "polylinker":"In photosynthetic cells, 	a functional set of light-absorbing pigments and its reaction 	center.",
    "polymerase chain reaetion (PCR)":"An organism that can use the energy of 	light to synthesize its own fuels from simple molecules such as 	carbon dioxide, oxygen, and water; as distinct from a chemotroph.",
    "polymorphic":"The negative logarithm of an equilibrium constant.",
    "polynucleotide":"The exterior membrane surrounding the 	cytoplasm of a cell.",
    "polypeptide":"The proteins present 	in blood plasma.",
    "polyribosome":"A phospholipid with an 	alkenyl ether substituent on the C-1 of glycerol.",
    "polysaccharide":"An 	extrachromosomal, independently replicating, small circular DNA 	molecule; commonly employed in genetic engineering.",
    "polysome (polyribosome)":"In 	plants, a self replicating organelle; may differentiate into a 	chloroplast.",
    "porphyrin":"Small, enucleated cells that 	initiate blood clotting; they arise from cells called megakaryocytes 	in the bone marrow. Also known as thrombocytes.",
    "positive cooperativity":"The side-by-side, hydrogen-bonded arrangement of polypeptide 	chains in the extended β conformation.",
    "posttranscriptional 	processing":"Hydrophilic, 	or 'water-loving'; describing molecules or groups that are 	soluble in water.",
    "pasttranslational modification":"(1) In chemistry, the 	nonuniform distribution of electrons in a molecule; polar molecules 	are usually soluble in water. (2) In molecular biology, the 	distinction between the 5' and 3' ends of nucleic acids.",
    "primary 	structure":"A heterogeneous pool of antibodies produced in an 	animal by a number of different B lymphocytes in response to an 	antigen. Different antibodies in the pool recognize different parts 	of the antigen.",
    "primary 	transcript":"A short, often synthetic, 	fragment of DNA containing recognition sequences for several 	restriction endonucleases.",
    "primase":"A 	repetitive procedure that results in a geometric amplification of a 	specific DNA sequence.",
    "primer":"Describing a protein 	for which amino acid sequence variants exist in a population of 	organisms, but the variations do not destroy the protein's function.",
    "probe":"A covalently linked sequence of nucleotides 	in which the 3' hydroxyl of the pentose of one nucleotide residue is 	joined by a phosphodiester bond to the 5' hydroxyl of the pentose of 	the next residue.",
    "processivity":"A long chain of amino acids 	linked by peptide bonds; the molecular weight is generally less than 	10,000.",
    "prochiral molecule":"See polysome.",
    "projection formulas":"A 	linear or branched polymer of monosaccharide units linked by 	glycosidic bonds.",
    "prokaryote":"A complex of an 	mRNA molecule and two or more ribo",
    "promoter":"Complex 	nitrogenous compound containing four substituted pyrroles covalently 	joined into a ring; often complexed with a central metal atom.",
    "prophage":"A phenomenon of some multisubunit 	enzymes or proteins in which binding of a ligand or substrate to one 	subunit facilitates binding to another subunit.",
    "prostaglandins":"The enzymatic processing of the primary RNA 	transcript, producing functional mRNA, tRNA, andJor rRNA molecules.",
    "prosthetic group":"Enzymatic processing of a 	polypeptide chain after translation from its mRNA.",
    "protein":"A description of the covalent backbone of a polymer 	(macromolecule), including the sequence of monomeric subunits and 	any interchain and intrachain covalent bonds.",
    "protein kinases":"The immediate RNA product of transcription before 	any posttranscriptional processing reactions.",
    "protein targeting":"An 	enzyme that catalyzes the formation of RNA oligonucleotides used as 	primers by DNA polymerases.",
    "proteoglycan":"A short oligomer (of 	sugars or nucleotides, for example) to which an enzyme adds 	additional monomeric subunits.",
    "proto-oncogene":"A labeled fragment of 	nucleic acid containing a nucleotide sequence complementary to a 	gene or genomic sequence that one wishes to detect in a 	hybridization experiment.",
    "proton acceptor":"For any enzyme that 	catalyzes the synthesis of a biological polymer, the property of 	adding multiple subunits to the polymer without dissociating from 	the substrate.",
    "proton 	donor":"A symmetric molecule 	that can react asymmetrically with an enzyme having an asymmetric 	active site, generating a chiral product.",
    "proton-motive force":"A method for representing molecules to show the configuration of 	groups around chiral centers; also known as Fischer projection 	formulas.",
    "protoplasm":"A bacterium; a unicellular organism 	with a single chromosome, no nuclear envelope, and no 	membranebounded organelles.",
    "purine":"A DNA sequence at 	which RNA polymerase may bind, leading to initiation of 	transcription.",
    "puromycin":"A bacteriophage in an inactive 	state in which the genome is either integrated into the chromosome 	of the host cell or (sometimes) replicated autonomously.",
    "pyranose":"A class of lipid-soluble, hormonelike 	regulatory molecules derived from arachidonate and other 	polyunsaturated fatty acids.",
    "pyridine nucleotide":"A metal ion 	or an organic compound (other than an amino acid) that is covalently 	bound to a protein and is essential to its activity.",
    "pyridoxal phosphate":"A 	macromolecule composed of one or more polypeptide chains, each with 	a characteristic sequence of amino acids linked by peptide bonds.",
    "pyrimidine":"Enzymes that phosphorylate certain amino 	acid residues in specific proteins.",
    "pyrimidine dimer":"The 	process by which newly synthesized proteins are sorted and 	transported to their proper locations in the cell.",
    "pyrophosphatase":"A hybrid macromolecule consisting of a heteropolysaccharide 	joined to a polypeptide; the polysaccharide is the major component.",
    "quantum":"A cellular gene, usually encoding a 	regulatory protein, that can be converted into an oncogene by 	mutation.",
    "quaternary structure":"An anionic compound capable of 	accepting a proton from a proton donor; that is, a base.",
    "R group":"The donor of a proton in an acid-base reaction; that is, 	an acid.",
    "racemic mixture tracemate)":"The electrochemical potential 	inherent in a transmembrane gradient of H+ 	concentration; used in oxidative phosphorylation and 	photophosphorylation to drive ATP synthesis.",
    "radical":"A 	general term referring to the entire contents of a living cell.",
    "radioactive isotope":"A nitrogenous heterocyclic base found in nucleotides 	and nucleic acids; containing fused pyrimidine and imidazole rings.",
    "radioimmunoassay":"An antibiotic that inhibits polypeptide synthesis 	by being incorporated into a growing polypeptide chain, causing its 	premature termination.",
    "rate-limiting step":"A simple sugar containing 	the six-membered pyran ring.",
    "reaction 	intermediate":"A 	nucleotide coenzyme containing the pyridine derivative nicotinamide; 	NAD or NADP.",
    "reading frame":"A coenzyme containing the 	vitamin pyridoxine (vitamin B6); 	functions in reactions involving amino group transfer.",
    "recombinant DNA":"A nitrogenous heterocyclic base found in nucleotides and 	nucleic acids.",
    "redox pair":"A covalently joined dimer 	of two adjacent pyrimidine residues in DNA, induced by absorption of 	ITV light; most commonly derived from two adjacent thymines (a 	thymine dimer).",
    "redox reaction":"See inorganic 	pyrophosphatase.",
    "reducing 	agent (reductant)":"The ultimate unit of energy.",
    "reducing end":"The three-dimensional structure of a 	multisubunit protein; particularly the manner in which the subunits 	fit together.",
    "reducing equivalent":"(1) Formally, an abbreviation 	denoting any alkyl group. (2) Occasionally, used in a more general 	sense to denote virtually any organic substituent tthe R groups of 	amino acids, for example).",
    "reducing sugar":"An 	equimolar mixture of the D and L 	stereoisomers of an optically active compound.",
    "reduction":"An 	atom or group of atoms possessing an unpaired electron; also called 	a free radical.",
    "regulatory 	enzyme":"An isotopic form of an 	element with an unstable nucleus that stabilizes itself by emitting 	ionizing radiation.",
    "regulatory gene":"A sensitive and 	quantitative method for detecting trace amounts of a biomolecule, 	based on its capacity to displace a radioactive form of the molecule 	from combination with its specific antibody.",
    "regulatory sequence":"(1) Generally, the step in an enzymatic reaction with the 	greatest activation energy or the transition state of highest free 	energy. (2) The slowest step in a metabolic pathway.",
    "regulon":"Any chemical species in a reaction pathway that 	has a finite chemical lifetime.",
    "release 	factors":"A contiguous 	and nonoverlapping set of three-nucleotide codons in DNA or RNA.",
    "releasing factors":"DNA formed by the joining of genes into new 	combinations.",
    "renaturation":"An electron donor and its 	corresponding oxidized form; for example, NADH and NAD+.",
    "replication":"See oxidation-reduction reaction.",
    "replisome":"The electron donor in an oxidation-reduction 	reaction.",
    "repressible enzyme":"The end of a polysaccharide having 	a terminal sugar with a free anomeric carbon; the terminal residue 	can act as a reducing sugar.",
    "repression":"A general 	or neutral term for an electron or an electron equivalent in the 	form of a hydrogen atom or a hydride ion.",
    "repressor":"A 	sugar in which the carbonyl (anomeric) carbon is not involved in a 	glycosidic bond and can therefore undergo oxidation.",
    "residue":"The gain of electrons by a compound or ion.",
    "respiration":"An enzyme having a regulatory function through its 	capacity to undergo a change in catalytic activity by allosteric 	mechanisms or by covalent modification.",
    "respiratory chain":"A 	gene that gives rise to a product involved in the regulation of the 	expression of another gene; for example, a gene coding for a 	repressor protein.",
    "restriction endonucleases":"A DNA sequence 	involved in regulating the expression of a gene; for example, a 	promoter or operator.",
    "restriction fragment":"A group of genes or operons 	that are coordinately regulated even though some, or all, may be 	spatially distant within the chromosome or genome.",
    "restriction fragment 	length polymorphisms (RFLPs)":"See termination factors.",
    "retrovirus":"Hypothalamic hormones that stimulate release of other hormones 	by the pituitary gland.",
    "reverse transcriptase":"Refolding of an 	unfolded (denatured) globular protein so as to restore native 	structure and protein function.",
    "ribonuclease":"Synthesis of a 	daughter duplex DNA molecule identical to the parental duplex DNA.",
    "ribonucleic 	acid":"The multiprotein complex that promotes DNA 	synthesis at the replication fork.",
    "ribonucleotide":"In 	bacteria, an enzyme whose synthesis is inhibited when its reaction 	product is readily available to the cell.",
    "ribosomal RNA (rRNA)":"A 	decrease in the expression of a gene in response to a change in the 	activity of a regulatory protein.",
    "ribosome":"The protein 	that binds to the regulatory sequence or operator for a gene, 	blocking its transcription.",
    "ribozymes":"A single unit within a 	polymer; for example, an amino acid within a polypeptide chain. The 	term reflects the fact that sugars, nucleotides, and amino acids 	lose a few atoms (generally the elements of water) when incorporated 	in their respective polymers.",
    "RNA (ribonucleic acid)":"The catabolic 	process in which electrons are removed from nutrient molecules and 	passed through a chain of carriers to oxygen.",
    "RNA polymerase":"The electron transfer chain; a sequence of electron-carrying 	proteins that transfer electrons from substrates to molecular oxygen 	in aerobic cells.",
    "RNA splicing":"Site-specific 	endodeoxyribonucleases causing cleavage of both strands of DNA at 	points within or near the specific site recognized by the enzyme; 	important tools in genetic engineering.",
    "rRNA":"A 	segment of double-stranded DNA produced by the action of a 	restriction endonuclease on a larger DNA.",
    "S-adenosylmethionine (adoMet)":"Variations, among individuals in 	a population, in the length of certain restriction fragments within 	which certain genomic sequences occur. These variations result from 	rare sequence changes that create or destroy restriction sites in 	the genome.",
    "salvage pathway":"An RNA virus containing a reverse 	transcriptase.",
    "saponification":"An RNA-directed DNA 	polymerase in retroviruses; capable of making DNA complementary to 	an RNA.",
    "sarcomere":"A nuclease that catalyzes the 	hydrolysis of certain internucleotide linkages of RNA.",
    "satellite DNA":"See RNA.",
    "saturated fatty 	acid":"A nucleotide containing 	n-ribose as its pentose component.",
    "second law of thermodynamics":"A 	class of RNA molecules serving as components of ribosomes.",
    "second messenger":"A supramolecular complex of rRNAs and proteins, 	approximately 18 to 22 nm in diameter; the site of protein 	synthesis.",
    "secondary metabolism":"Ribonucleic acid molecules with 	catalytic activities; RNA enzymes.",
    "secondary structure":"A 	polyribonucleotide of a specific sequence linked by successive 	3',5'-phosphodiester bonds.",
    "sedimentation coefficient":"An enzyme that 	catalyzes the formation of RNA from ribonucleoside 5'-triphosphates, 	using a strand of DNA or RNA as a template.",
    "Shine-Dalgarno 	sequence":"Removal of introns and joining of exons in a primary transcript.",
    "shuttle vector":"See ribosomal RNA.",
    "sickle-cell anemia":"An enzymatic cofactor involved in methyl group transfers.",
    "sickle-cell trait":"Synthesis of a biomolecule, such as a 	nucleotide, from intermediates in the degradative pathway for the 	biomolecule; a recycling pathway, as distinct from a de novo 	pathway.",
    "signal sequence":"Alkaline hydrolysis of 	triacylglycerols to yield fatty acids as soaps.",
    "signal transduction":"A 	functional and structural unit of the muscle contractile system.",
    "silent 	mutation":"Highly repeated, nontranslated segments of 	DNA in eukaryotic chromosomes; most often associated with the 	centromeric region. Its function is not clear.",
    "simple 	diffusion":"A fatty acid containing a fully saturated alkyl chain.",
    "simple protein":"The law stating that in any 	chemical or physical process, the entropy of the universe tends to 	increase.",
    "site-directed mutagenesis":"An effector molecule 	synthesized within a cell in response to an external signal (first 	messenger) such as a hormone.",
    "site-specific recombination":"Pathways 	that lead to specialized products not found in every living cell.",
    "small 	nuclear RNA (snRNA)":"The residue-byresidue conformation of 	the backbone of a polymer.",
    "somatic cells":"A 	physical constant specifying the rate of sedimentation of a particle 	in a centrifugal field under specified conditions.",
    "SOS response":"A sequence in an mRNA required for binding 	prokaryotic ribosomes.",
    "Southern blot":"A recombinant DNA 	vector that can be replicated in two or more different host species. 	See also vector.",
    "specific activity":"A human disease 	characterized by defective hemoglobin molecules; caused by a 	homozygous allele coding for the β chain of hemoglobin.",
    "specific heat":"A human condition recognized by the 	sickling of erythrocytes when exposed to low oxygen tension; occurs 	in individuals heterozygous for the allele responsible for 	sickle-cell anemia.",
    "specific rotation":"An amino-terminal 	sequence that signals the cellular fate or destination of a newly 	synthesized protein.",
    "specificity":"The process by 	which an extracellular signal (chemical, mechanical, or electrical) 	is amplified and converted to a cellular response.",
    "sphingolipid":"A mutation in a gene that causes no detectable change 	in the biological characteristics of the gene product.",
    "splicing":"The movement of solute molecules across a membrane 	to a region of lower concentration, unassisted by a protein 	transporter.",
    "standard free-energy change (ΔG°)":"A protein yielding only amino 	acids on hydrolysis.",
    "standard reduction 	potential (E0')":"A set of 	methods used to create specific alterations in the sequence of a 	gene.",
    "steady state":"A type of genetic 	recombination that occurs only at specific ssquences.",
    "stem cells":"Any of several small RNA molecules in the 	nucleus; most have a role in the splicing reactions that remove 	introns from mRNA, tRNA, and rRNA molecules.",
    "? 	stereoisomers":"All 	body cells except the germ-line cells.",
    "sterols":"In 	bacteria, a coordinated induction of a variety of genes as a 	response to high levels of DNA damage.",
    "sticky ends":"A DNA 	hybridization procedure in which one or more specific DNA fragments 	are detected in a larger population by means of hybridization to a 	complementary, labeled nucleic acid probe.",
    "stop codons":"The number of micromoles (μmol) of a substrate transformed by 	an enzyme preparation per minute per milligram of protein at 25°C; 	a measure of enzyme purity.",
    "stroma":"The amount of 	energy (in joules or calories) needed to raise the temperature of 1 	g of a pure substance by 1 °C.",
    "structural gene":"The 	rotation, in degrees, of the plane of plane-polarized light (D-line 	of sodium) by an optically active compound at 25 °C, with a 	specified concentration and light path.",
    "substitution 	mutation":"The 	ability of an enzyme or receptor to discriminate among competing 	substrates or ligands.",
    "substrate":"An amphipathic lipid 	with a sphingosine backbone to which are attached a long-chain fatty 	acid and a polar alcohol.",
    "substrate-level phosphorylation":"See gene splicing; RNA 	splicing.",
    "suicide inhibitor":"The 	free-energy change for a reaction occurring under a set of standard 	conditions : temperature, 298 K; pressure, 1 atm or 101.3 kPa; and 	all solutes at 1 ni concentration. ΔG°' denotes the 	standard free-energy change at pH 7.0.",
    "suppressor mutation":"",
    "Svedberg (S)":"",
    "symbionts":"The 	electromotive force exhibited at an electrode by 1 M 	concentrations of a reducing agent and its oxidized form at 25 °C 	and pH 7.0; a measure of the relative tendency of the reducing agent 	to lose electrons.",
    "symport":"A nonequilibrium state of 	a system through which matter is flowing and in which all components 	remain at a constant concentration.",
    "synthases":"The common, 	self regenerating cells in bone marrow that give rise to 	differentiated blood cells such as erythrocytes and lymphocytes.",
    "synthetases":"Compounds that have the same composition and the 	same order of atomic connections, but different molecular 	arrangements.",
    "system":"A class of lipids containing the 	steroid nucleus.",
    "telomere":"Two DNA ends in the same DNA 	molecule, or in different molecules, with short overhanging 	single-stranded segments that are complementary to one another, 	facilitating ligation of the ends; also known as cohesive ends.",
    "temperate phage":"See termination codons.",
    "template":"The 	space and aqueous solution enclosed within the inner membrane of a 	chloroplast, not including the contents within the thylakoid 	membranes.",
    "terminal transferase":"A gene coding for a protein or 	RNA molecule; as distinct from a regulatory gene.",
    "termination codons":"A mutation caused by the replacement of one base by 	another.",
    "termination 	factors":"The specific compound acted upon by an 	enzyme.",
    "termination sequence":"Phosphorylation of 	ADP or some other nucleoside 5'-diphosphate coupled to the 	dehydrogenation of an organic substrate; independent of the electron 	transfer chain.",
    "terpenes":"A relatively inert 	molecule that is transformed by an enzyme, at its active site, into 	a reactive substance that irreversibly inactivates the enzyme.",
    "tertiary 	structure":"A mutation that totally or partially 	restores a function lost by a primary mutation; located at a site 	different from the site of the primary mutation.",
    "tetrahydrobiopterin":"A unit of measure of the rate at which a particle sediments in a 	centrifugal field.",
    "tetrahydrofolate":"Two or more organisms that 	are mutually interdependent; usually Iiving in physical association.",
    "thiamine 	pyrophosphate":"Cotransport of solutes across a membrane in the 	same direction.",
    "thioester":"Enzymes that catalyze 	condensation reactions in which no nucleoside triphosphate is 	required as an energy source.",
    "3' end":"Enzymes that 	catalyze candensation reactions using ATP or another nucleoside 	triphosphate as an energy source.",
    "thrombocytes":"An isolated 	collection of matter; all other matter in the universe apart from 	the system is called the surroundings.",
    "thromboxanes":"Specialized 	nucleic acid structure found at the ends of linear eukaryotic 	chromosomes.",
    "thylakoid":"A phage whose DNA may be 	incorporated into the host-cell genome without being expressed; as 	distinct from a virulent phage, which destroys the host cell.",
    "thymine 	dimer":"A macromolecular mold or pattern for the synthesis 	of an informational macromolecule.",
    "tissue culture":"An 	enzyme that catalyzes the addition of nucleotide residues of a 	single kind to the 3' end of DNA chains.",
    "titration curve":"UAA, UAG, and UGA; in protein synthesis, signal the termination 	of a polypeptide chain. Also known as stop codons.",
    "tocopherols":"Protein factors of the cytosol required in releasing a 	completed polypeptide chain from a ribosome; also known as release 	factors.",
    "topoisomerases":"A DNA sequence that appears 	at the end of a transcriptional unit and signals the end of 	transcription.",
    "topoisomers":"Organic hydrocarbons or 	hydrocarbon derivatives constructed from recurring isoprene units. 	They produce some of the scents and tastes of plant products; for 	example, the scents of geranium leaves and pine needles.",
    "toxins":"The three-dimensional conformation of a polymer in 	its native folded state.",
    "trace element":"The reduced 	coenzyme form of biopterin.",
    "transaminases":"The reduced, 	active coenzyme form of the vitamin folate.",
    "transamination":"The active coenzyme form of vitamin Bl; 	involved in aldehyde transfer reactions.",
    "transcription":"An 	ester of a carboxylic acid with a thiol or mercaptan.",
    "transcriptional control":"The end of a nucleic acid that lacks a nucleotide bound at the 	3' position of the terminal residue.",
    "transduction":"See 	platelets.",
    "transfer RNA (tRNA)":"A class of molecules derived from 	arachidonate and involved in platelet aggregation during blood 	clotting.",
    "transformation":"Closed cisterna, or disc, formed by 	the pigment-bearing internal membranes of chloroplasts.",
    "transgenic":"See pyrimidine dimer.",
    "transition 	state":"Method by 	which cells derived from multicellular organisms are grown in liquid 	media.",
    "translation":"A plot of the pH versus the 	equivalents of base added during titration of an acid.",
    "translational 	control":"Forms of vitamin E.",
    "translational 	repressor":"Enzymes that 	introduce positive or negative supercoils in closed, circular duplex 	DNA.",
    "translocase":"Different forms of a covalently closed, 	circular DNA molecule that differ only in their linking number.",
    "transpiration":"Proteins produced by some organisms and toxic to 	certain other species.",
    "transporters":"A chemical element 	required by an organism in only trace amounts.",
    "transposition":"See aminotransferases.",
    "transposon 	(transposable element)":"Enzymatic 	transfer of an amino group from an α-amino acid to an α-keto 	acid.",
    "triacylglycerol":"The enzymatic process whereby the 	genetic information contained in one strand of DNA is used to 	specify a complementary sequence of bases in an mRNA chain.",
    "tricarboxylic acid cycle":"The regulation of a protein's 	synthesis by regulation of the formation of its mRNA.",
    "triose":"(1) Generally, the conversion of energy or information from one 	form to another. (2) The transfer of genetic information from one 	cell to another by means of a viral vector.",
    "tRNA":"A class of RNA molecules (Mr. 25,000 to 	30,000), each of which combines covalently with a specific amino 	acid as the first step in protein synthesis.",
    "tropic hormone (tropin)":"Introduction of an exogenous DNA into a cell, causing the cell 	to acquire a new phenotype.",
    "turnover number":"Describing an 	organism that has genes from another organism incorporated within 	its genome as a result of recombinant DNA procedures.",
    "ultraviolet (UV) radiation":"An activated form of a molecule in which the molecule 	has undergone a partial chemical reaction; the highest point on the 	reaction coordinate.",
    "uncoupling agent":"The process in which the 	genetic information present in an mRNA molecule specifies the 	sequence of amino acids during protein synthesis.",
    "uniport":"The regulation of a protein's synthesis by regulation 	of the rate of its translation on the ribosome.",
    "unsaturated fatty acid":"A repressor that binds to an mRNA, blocking 	translation.",
    "urea cycle":"(1) An enzyme that catalyzes 	membrane transport. (2) An enzyme that causes a movement, such as 	the movement of a ribosome along an mRNA.",
    "ureotelic":"Passage of water from the roots of a plant to the atmosphere via 	the vascular system and the stomata of the leaves.",
    "uricotelic":"Proteins that span a membrane and transport specific nutrients, 	metabolites, ions, or proteins across the membrane; sometimes called 	permeases.",
    "Vmax":"The movement of a gene or set of 	genes from one site in the genome to another.",
    "vector":"A segment of DNA that can move from one 	position in the genome to another.",
    "viral vector":"An 	ester of glycerol with three molecules of fatty acid; also called a 	triglyceride or neutral fat.",
    "virion":"See 	citric acid cycle.",
    "virus":"A simple sugar with a backbone 	containing three carbon atoms.",
    "vitamin":"See transfer RNA.",
    "wild 	type":"A peptide hormone that stimulates a 	specific target gland to secrete its hormone; for example, 	thyrotropin produced by the pituitary stimulates secretion of 	thyroxine by the thyroid.",
    "wobble":"The number of 	times an enzyme molecule transforms a substrate molecule per unit 	time, under conditions giving maximal activity at substrate 	concentrations that are saturating.",
    "x-ray crystallography":"Electromagnetic radiation in the region of 200 to 400 nm.",
    "zinc finger":"A substance that uncouples phosphorylation 	of ADP from electron transfer; for example, 2,4-dinitrophenol.",
    "zwitterion":"A transport system that carries only one solute, as 	distinct from cotransport.",
    "zymogen":"A fatty 	acid containing one or more double bonds.", }
